import type { DemoCapability, DemoTenant, IndustryData } from "./types";

export const demoTenants: DemoTenant[] = [
  {
    id: "leasing",
    name: "浦银金融租赁股份有限公司",
    shortName: "浦银金租",
    defaultUser: { id: "leasing_user_001", name: "张经理", role: "客户经理" },
    enabledCapabilities: ["industry_research"],
    plannedCapabilities: [
      "customer_operation",
      "project_analysis",
      "risk_analysis",
    ],
  },
  {
    id: "wealth",
    name: "浦银理财有限责任公司",
    shortName: "浦银理财",
    defaultUser: { id: "wealth_user_001", name: "李老师", role: "研究员" },
    enabledCapabilities: ["industry_research"],
    plannedCapabilities: [
      "investment_strategy",
      "issuer_research",
      "data_analysis",
    ],
  },
  {
    id: "trust",
    name: "上海国际信托有限公司",
    shortName: "上海信托",
    defaultUser: { id: "trust_user_001", name: "王老师", role: "项目经理" },
    enabledCapabilities: ["industry_research"],
    plannedCapabilities: [
      "project_due_diligence",
      "asset_research",
      "risk_analysis",
    ],
  },
  {
    id: "international",
    name: "浦银国际",
    shortName: "浦银国际",
    defaultUser: {
      id: "international_user_001",
      name: "陈老师",
      role: "投资银行业务人员",
    },
    enabledCapabilities: ["industry_research"],
    plannedCapabilities: ["company_research", "ipo_research", "ma_analysis"],
  },
];

export const capabilities: DemoCapability[] = [
  {
    id: "industry_research",
    name: "产业智能研究",
    description: "产业链、企业、政策与风险综合研究",
    status: "enabled",
  },
  {
    id: "data_analysis",
    name: "数据分析",
    description: "指标查询、经营分析与趋势洞察",
    status: "coming_soon",
  },
  {
    id: "customer_operation",
    name: "客户经营",
    description: "目标客户发现、客户画像与营销机会分析",
    status: "coming_soon",
  },
  {
    id: "project_analysis",
    name: "项目分析",
    description: "项目结构、收益与风险综合分析",
    status: "coming_soon",
  },
  {
    id: "risk_analysis",
    name: "风险分析",
    description: "企业、行业与项目风险综合分析",
    status: "coming_soon",
  },
  {
    id: "investment_strategy",
    name: "投研策略",
    description: "市场研判与投资策略辅助",
    status: "coming_soon",
  },
  {
    id: "issuer_research",
    name: "发行人研究",
    description: "发行人基本面与信用研究",
    status: "coming_soon",
  },
  {
    id: "project_due_diligence",
    name: "项目尽调",
    description: "项目背景、主体、行业与风险尽调",
    status: "coming_soon",
  },
  {
    id: "asset_research",
    name: "资产研究",
    description: "资产质量与价值分析",
    status: "coming_soon",
  },
  {
    id: "company_research",
    name: "公司研究",
    description: "上市公司与目标企业研究",
    status: "coming_soon",
  },
  {
    id: "ipo_research",
    name: "IPO 研究",
    description: "IPO 项目与行业比较分析",
    status: "coming_soon",
  },
  {
    id: "ma_analysis",
    name: "并购分析",
    description: "并购标的与协同价值分析",
    status: "coming_soon",
  },
];

const commonPolicies = (topic: string) => [
  {
    id: `${topic}_p1`,
    title: `${topic}产业高质量发展行动方案（演示）`,
    level: "国家",
    date: "2026-06-01",
    tags: [topic, "产业升级"],
    summary: "支持核心技术突破、产业链协同和规模化应用。",
  },
  {
    id: `${topic}_p2`,
    title: `${topic}产业专项支持政策（演示）`,
    level: "地方",
    date: "2026-03-18",
    tags: [topic, "智能制造"],
    summary: "鼓励重点项目落地与产业集群建设。",
  },
];

export const industries: Record<string, IndustryData> = {
  robotics: {
    id: "robotics",
    name: "机器人",
    description:
      "产业化提速，核心零部件国产化与人形机器人商业化是主要观察线索。",
    overview: {
      marketSize: "5,800亿元",
      prosperityIndex: 78,
      companyCount: 12,
      policyCount: 8,
    },
    trend: [
      { month: "4月", value: 66 },
      { month: "5月", value: 68 },
      { month: "6月", value: 71 },
      { month: "7月", value: 73 },
      { month: "8月", value: 76 },
      { month: "9月", value: 78 },
    ],
    chain: {
      upstream: ["减速器", "伺服系统", "控制器", "传感器"],
      midstream: ["工业机器人", "协作机器人", "人形机器人"],
      downstream: ["汽车", "3C电子", "新能源", "物流"],
    },
    companies: [
      {
        id: "inovance",
        name: "汇川技术",
        stage: "上游",
        field: "伺服系统",
        competitiveness: "高",
        prosperity: "高",
        risk: "中",
        products: "伺服系统、控制器、工业自动化解决方案",
        revenue: [161, 230, 304, 367],
        grossMargin: "35.8%",
        researchRatio: "9.4%",
        riskIndex: 42,
      },
      {
        id: "leaderdrive",
        name: "绿的谐波",
        stage: "上游",
        field: "减速器",
        competitiveness: "高",
        prosperity: "高",
        risk: "中",
        products: "谐波减速器、机电一体化产品",
        revenue: [4.4, 4.5, 3.6, 5.1],
        grossMargin: "41.2%",
        researchRatio: "12.1%",
        riskIndex: 46,
      },
      {
        id: "estun",
        name: "埃斯顿",
        stage: "中游",
        field: "工业机器人",
        competitiveness: "较高",
        prosperity: "中高",
        risk: "中",
        products: "工业机器人、运动控制系统",
        revenue: [30, 39, 47, 55],
        grossMargin: "31.6%",
        researchRatio: "11.8%",
        riskIndex: 49,
      },
    ],
    risks: [
      "核心零部件价格上涨",
      "人形机器人商业化进度低于预期",
      "下游制造业资本开支回落",
      "行业竞争加剧带来价格压力",
    ],
    policies: commonPolicies("机器人"),
  },
  lithium: {
    id: "lithium",
    name: "锂电池",
    description: "供需再平衡与储能需求增长并行，资源价格波动仍是主要传导变量。",
    overview: {
      marketSize: "9,200亿元",
      prosperityIndex: 72,
      companyCount: 18,
      policyCount: 10,
    },
    trend: [
      { month: "4月", value: 69 },
      { month: "5月", value: 68 },
      { month: "6月", value: 70 },
      { month: "7月", value: 71 },
      { month: "8月", value: 73 },
      { month: "9月", value: 72 },
    ],
    chain: {
      upstream: ["锂矿", "正极材料", "负极材料", "电解液"],
      midstream: ["电芯", "电池管理系统", "电池包"],
      downstream: ["新能源汽车", "储能", "消费电子"],
    },
    companies: [
      {
        id: "catl",
        name: "宁德时代",
        stage: "中游",
        field: "动力电池",
        competitiveness: "高",
        prosperity: "高",
        risk: "中",
        products: "动力电池、储能电池、换电服务",
        revenue: [2970, 3286, 4009, 4520],
        grossMargin: "26.1%",
        researchRatio: "5.9%",
        riskIndex: 38,
      },
    ],
    risks: [
      "锂资源价格快速反弹",
      "海外贸易政策变化",
      "产能扩张导致阶段性过剩",
      "技术路线迭代风险",
    ],
    policies: commonPolicies("锂电池"),
  },
  semiconductor: {
    id: "semiconductor",
    name: "半导体",
    description:
      "国产替代与AI算力需求推动景气修复，设备材料和先进封装相对活跃。",
    overview: {
      marketSize: "1.5万亿元",
      prosperityIndex: 75,
      companyCount: 16,
      policyCount: 12,
    },
    trend: [
      { month: "4月", value: 64 },
      { month: "5月", value: 67 },
      { month: "6月", value: 69 },
      { month: "7月", value: 71 },
      { month: "8月", value: 73 },
      { month: "9月", value: 75 },
    ],
    chain: {
      upstream: ["设备", "材料", "EDA", "IP"],
      midstream: ["设计", "制造", "封测"],
      downstream: ["AI算力", "汽车电子", "消费电子", "工业控制"],
    },
    companies: [
      {
        id: "smic",
        name: "中芯国际",
        stage: "中游",
        field: "晶圆制造",
        competitiveness: "高",
        prosperity: "中高",
        risk: "中",
        products: "晶圆代工与配套技术服务",
        revenue: [495, 462, 577, 680],
        grossMargin: "20.6%",
        researchRatio: "12.4%",
        riskIndex: 45,
      },
    ],
    risks: [
      "外部技术限制",
      "先进制程投入压力",
      "终端需求复苏不均衡",
      "供应链区域化成本上升",
    ],
    policies: commonPolicies("半导体"),
  },
};

export const operationsMock = {
  overview: {
    activeUsers: 1286,
    activeTenants: 4,
    aiCalls: 42368,
    researchTasks: 8421,
    reports: 2103,
    avgResponseSeconds: 3.2,
  },
  tenantUsage: [
    { name: "浦银金租", value: 36 },
    { name: "浦银理财", value: 29 },
    { name: "上海信托", value: 21 },
    { name: "浦银国际", value: 14 },
  ],
  trend: [
    { day: "9/23", users: 720, calls: 4680 },
    { day: "9/24", users: 810, calls: 5120 },
    { day: "9/25", users: 940, calls: 5980 },
    { day: "9/26", users: 1060, calls: 6540 },
    { day: "9/27", users: 1120, calls: 6810 },
    { day: "9/28", users: 1190, calls: 7020 },
    { day: "9/29", users: 1286, calls: 7218 },
  ],
};
